kind: pipeline
name: default
type: docker

steps:
  - name: publish
    image: plugins/docker
    settings:
      username: nologin
      password:
        from_secret: docker_password
      repo: rg.fr-par.scw.cloud/jlelse/goshort
      registry: rg.fr-par.scw.cloud/jlelse
      tags: latest
      mirror: https://mirror.gcr.io

trigger:
  branch:
    - master
  event:
    - push