kind: pipeline
name: default
type: docker

steps:
  - name: publish
    image: plugins/docker
    settings:
      username: nologin
      password:
        from_secret: docker_password
      repo: git.jlel.se/jlelse/goshort
      registry: git.jlel.se
      tags: latest
      mirror: https://mirror.gcr.io

trigger:
  branch:
    - master
  event:
    - push